#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'script.sh' using that shell.
#
#       (b) If your shell is not POSIX-compliant, you may see "Bad substitution"
#           errors. To fix, ensure you have the latest version of Gradle installed
#           and the script is using the latest Gradle wrapper.
#
#   (c) The script uses '/bin/sh' shebang, but since not all POSIX shells are
#       located at /bin/sh, you can set the PATH environment variable to include
#       the directory of your POSIX shell. Alternatively, you can change the
#       shebang to point to your POSIX shell.
#
#   (d) The script uses command substitution and pipes heavily. If your shell
#       does not support these features, you may see errors. To fix, upgrade to
#       a more modern shell (e.g. bash).
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Use the maximum available file descriptors if possible.
if command -v ulimit > /dev/null 2>&1 && ulimit -n -H -s > /dev/null 2>&1; then
    ulimit -n -H -s 2>&1 | grep -q "unlimited" || ulimit -n -s 65536 2>&1
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * $0 and $1 are the current script and command (default .gradlew/gradlew)
#   * The remainder are the arguments to the gradle command (excluding the gradle wrapper script)
#     These are split using eval so we can pass --args later.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs > /dev/null 2>&1; then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#   readarray -t args < <( xargs -n1 <<<"$var" ) &&
#   set -- "${args[@]}" "$@"
#
# But POSIX shell has neither arrays nor command substitution with process
# substitution. Instead we use a subshell and eval to build the arguments.
#
# The following reads from the command line arguments into a variable "args".
# This is safe because $@ expands to all arguments, and printf will interpret
# escape sequences (like \n) which we don't want. To avoid that, we use printf
# %q to quote each argument.
eval "set -- $(printf '%s ' "$DEFAULT_JVM_OPTS" | xargs -n1 | sed 's/^/"/;s/$/"/') $(printf '%s ' "$JAVA_OPTS" | xargs -n1 | sed 's/^/"/;s/$/"/') $(printf '%s ' "$GRADLE_OPTS" | xargs -n1 | sed 's/^/"/;s/$/"/')" '"$@"'

# Execute Gradle
exec "$JAVACMD" "$@"
